openapi: 3.0.0
info:
  title: Supabase GoTrue
  description: "A JWT based API for managing users and issuing JWT tokens "
  version: 0.0.1
paths:
  /token:
    summary: This is an OAuth2 endpoint that currently implements the password and refresh_token grant types
    post:
      parameters:
        - name: grant_type
          in: query
          required: true
          schema:
            type: string
            enum:
              - password
              - refresh_token
        - $ref: "#/components/parameters/redirect_url"
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenRequest"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
  /signup:
    summary: ""
    post:
      parameters:
        - $ref: "#/components/parameters/redirect_url"
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpRequest"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Session"
                  - $ref: "#/components/schemas/User"
components:
  parameters:
    redirect_url:
      name: redirect_url
      in: query
      schema:
        type: string
        format: uri
  schemas:
    TokenRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        phone:
          type: string
        refresh_token:
          type: string
    SignUpRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        phone:
          type: string
        data:
          type: object
        gotrue_meta_security:
          format: object
          properties:
            hcaptcha_token:
              type: string
    Session:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: number
        refresh_token:
          type: string
        user:
          $ref: "#/components/schemas/User"
      required:
        - access_token
        - token_type
        - expires_in
        - refresh_token
        - user
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        app_metadata:
          type: object
        user_metadata:
          type: object
        aud:
          type: string
        confirmation_sent_at:
          type: string
          format: date-time
        recovery_sent_at:
          type: string
          format: date-time
        invited_at:
          type: string
          format: date-time
        action_link:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        created_at:
          type: string
          format: date-time
        confirmed_at:
          type: string
          format: date-time
        email_confirmed_at:
          type: string
          format: date-time
        phone_confirmed_at:
          type: string
          format: date-time
        last_sign_in_at:
          type: string
          format: date-time
        role:
          type: string
        updated_at:
          type: string
          format: date-time
        identities:
          type: array
          items:
            $ref: "#/components/schemas/UserIdentity"
      required:
        - id
        - app_metadata
        - user_metadata
        - aud
        - created_at
        - updated_at
    UserIdentity:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        identity_data:
          type: object
        provider:
          type: string
        created_at:
          type: string
          format: date-time
        last_sign_in_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - user_id
        - identity_data
        - provider
        - created_at
        - last_sign_in_at
        - updated_at
